"""lat/lon/depth/tags/comments

Revision ID: 16bb7a50388b
Revises: None
Create Date: 2015-10-07 17:44:57.247695

"""

# revision identifiers, used by Alembic.
revision = '16bb7a50388b'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    eval("upgrade_%s" % engine_name)()


def downgrade(engine_name):
    eval("downgrade_%s" % engine_name)()





def upgrade_dashboard():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bin_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bin_id', sa.Integer(), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['bin_id'], ['bins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bin_comments_comment', 'bin_comments', ['comment'], unique=False)
    op.create_table('bin_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bin_id', sa.Integer(), nullable=True),
    sa.Column('tag', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['bin_id'], ['bins.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bin_id', 'tag')
    )
    op.create_index('ix_bin_tags_tag', 'bin_tags', ['tag'], unique=False)
    op.add_column(u'bins', sa.Column('depth', sa.Numeric(), nullable=True))
    op.add_column(u'bins', sa.Column('lat', sa.Numeric(), nullable=True))
    op.add_column(u'bins', sa.Column('lon', sa.Numeric(), nullable=True))
    op.create_index('ix_bins_depth', 'bins', ['depth'], unique=False)
    op.create_index('ix_bins_lat', 'bins', ['lat'], unique=False)
    op.create_index('ix_bins_lon', 'bins', ['lon'], unique=False)
    ### end Alembic commands ###


def downgrade_dashboard():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bins_lon', 'bins')
    op.drop_index('ix_bins_lat', 'bins')
    op.drop_index('ix_bins_depth', 'bins')
    op.drop_column(u'bins', 'lon')
    op.drop_column(u'bins', 'lat')
    op.drop_column(u'bins', 'depth')
    op.drop_index('ix_bin_tags_tag', 'bin_tags')
    op.drop_table('bin_tags')
    op.drop_index('ix_bin_comments_comment', 'bin_comments')
    op.drop_table('bin_comments')
    ### end Alembic commands ###

